restaurant/urls.py
from django.urls import path

from restaurant.views import (index,
                              PastaListView,
                              PastaDetailView,
                              CookerDetailView,
                              PizzaListView,
                              PizzaDetailView,
                              AperitifsListView,
                              AperitifsDetailView,
                              SaladListView,
                              SaladDetailView,
                              MainDishesListView,
                              MainDishesDetailView,
                              DessertsListView,
                              DessertsDetailView,
                              )

urlpatterns = [
    path("", index, name="index"),
    path("cooker/<int:pk>/", CookerDetailView.as_view(), name="cooker-detail"),
    path("pasta/", PastaListView.as_view(), name="pasta-list"),
    path("pasta/<int:pk>/", PastaDetailView.as_view(), name="pasta-detail"),
    path("pizza/", PizzaListView.as_view(), name="pizza-list"),
    path("pizza/<int:pk>/", PizzaDetailView.as_view(), name="pizza-detail"),
    path("aperitifs/", AperitifsListView.as_view(), name="aperitifs-list"),
    path("aperitifs/<int:pk>/", AperitifsDetailView.as_view(), name="aperitifs-detail"),
    path("salads/", SaladListView.as_view(), name="salad-list"),
    path("salads/<int:pk>/", SaladDetailView.as_view(), name="salad-detail"),
    path("dishes/", MainDishesListView.as_view(), name="main-dishes-list"),
    path("dishes/<int:pk>/", MainDishesDetailView.as_view(), name="main-dishes-detail"),
    path("desserts/", DessertsListView.as_view(), name="desserts-list"),
    path("deserts/<int:pk>/", DessertsDetailView.as_view(), name="desserts-detail"),

]

app_name = "catalog"

restaurant_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("restaurant.urls", namespace="catalog")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class DishType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=63)
    description = models.TextField(max_length=255)
    price = models.DecimalField(max_digits=2, decimal_places=1)
    dish_type = models.ForeignKey("DishType", on_delete=models.CASCADE)
    cookers = models.ManyToManyField(
        "Cook",
        related_name="cooked_dishes"
    )

    def __str__(self):
        return f"{self.name}"


class Cook(AbstractUser):
    years_of_experience = models.PositiveIntegerField(default=1)
    dishes = models.ManyToManyField("Dish", related_name="cooks_preparing")

    class Meta:
        verbose_name = "cooker"
        verbose_name_plural = "cookers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

restaurant/forms.py
from django import forms

restaurant/views.py
from django.views import generic
from django.shortcuts import render
from restaurant.models import Dish, Cook, DishType
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    num_dish_types = DishType.objects.all()
    num_dishes = Dish.objects.all()
    num_cookers = Cook.objects.all()

    context = {
        "num_dish_types": num_dish_types,
        "num_dishes": num_dishes,
        "num_cookers": num_cookers,
    }

    return render(request, "restaurant/index.html", context=context)


class CookerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    template_name = "restaurant/cooker_detail.html"


class PastaListView(generic.ListView):
    queryset = Dish.objects.filter(dish_type__name__icontains="pasta")
    context_object_name = "pasta_list"
    template_name = "restaurant/pasta_list.html"


class PastaDetailView(generic.DetailView):
    model = Dish
    template_name = "restaurant/pasta_detail.html"


class PizzaListView(generic.ListView):
    queryset = Dish.objects.filter(dish_type__name__icontains="pizza")
    context_object_name = "pizza_list"
    template_name = "restaurant/pizza_list.html"


class PizzaDetailView(generic.DetailView):
    model = Dish
    template_name = "restaurant/pizza_detail.html"


class AperitifsListView(generic.ListView):
    queryset = Dish.objects.filter(dish_type__name__icontains="aperitif")
    context_object_name = "aperitifs_list"
    template_name = "restaurant/aperitifs_list.html"


class AperitifsDetailView(generic.DetailView):
    model = Dish
    template_name = "restaurant/aperitifs_detail.html"


class SaladListView(generic.ListView):
    queryset = Dish.objects.filter(dish_type__name__icontains="salad")
    context_object_name = "salads_list"
    template_name = "restaurant/salads_list.html"


class SaladDetailView(generic.DetailView):
    model = Dish
    template_name = "restaurant/salads_detail.html"


class MainDishesListView(generic.ListView):
    queryset = Dish.objects.filter(dish_type__name__icontains="dishes")
    context_object_name = "dish_list"
    template_name = "restaurant/main_dishes_list.html"


class MainDishesDetailView(generic.DetailView):
    model = Dish
    template_name = "restaurant/main_dishes_detail.html"


class DessertsListView(generic.ListView):
    queryset = Dish.objects.filter(dish_type__name__icontains="desserts")
    context_object_name = "desserts_list"
    template_name = "restaurant/desserts_list.html"


class DessertsDetailView(generic.DetailView):
    model = Dish
    template_name = "restaurant/desserts_detail.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% block sidebar %}{% include "includes/sidebar_main.html" %}{% endblock %}
{% block content %}{% endblock %}
{% block footer %} {% include "includes/footer.html" %} {% endblock %}
{% block js_scripts %}{% include "includes/js_scripts.html" %}{% endblock %}
</body>
</html>

templates/includes/footer.html
<footer class="footer fixed-bottom bg-success">
  <div class="container-footer">
  <div class="col-sm-9">
    <span class="text-white">This forum is optimized for communication and sharing culinary experiences.
      Lessons, tips and examples are reviewed regularly to avoid errors. By
      using this forum, you agree that you have read and accepted our terms
      of use, as well as our cookie and privacy policies. <i class="far fa-copyright"></i></span>
  </div>
</div>
</footer>

templates/includes/js_scripts.html
<script src="https://kit.fontawesome.com/70dbb55011.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/includes/sidebar_main.html
<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <a class="navbar-brand" href="{% url 'catalog:index' %}"><span style="color: gold">La Dolce</span> Vita</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'catalog:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'catalog:cooker-detail' pk=user.id %}">Profile</a>
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Catalog
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'catalog:pasta-list' %}">Pasta</a>
          <a class="dropdown-item" href="{% url 'catalog:pizza-list' %}">Pizza</a>
          <a class="dropdown-item" href="{% url 'catalog:aperitifs-list' %}">Aperitifs</a>
          <a class="dropdown-item" href="{% url 'catalog:salad-list' %}">Salads</a>
          <a class="dropdown-item" href="{% url 'catalog:main-dishes-list' %}">Main Dishes</a>
          <a class="dropdown-item" href="{% url 'catalog:desserts-list' %}">Desserts</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      {% if user.is_authenticated %}
        <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}"><button type="button" class="btn btn-gray">Logout</button></a></li>
      {% else %}
        <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}"><button type="button" class="btn btn-gray">Login <i class="fa-solid fa-right-to-bracket"></i></button></a></li>
      {% endif %}
    </form>
  </div>
</nav>

templates/restaurant/aperitifs_detail.html
{% extends "base.html" %}
{% block content %}
  <h3 style="text-align: center">Detail {{ dish.dish_type.name }} Page</h3>
  <hr>
  <div class="row justify-content-center">
    <div class="detail-page">
      <p><strong>Aperitif name:</strong> {{ dish.name }}</p>
      <p><strong>Aperitif name:</strong> {{ dish.price }}</p>
      <p><strong>Aperitif description: <br> {{ dish.description }}</strong></p>
      {% if dish.cookers%}
        <h5>Cookers:</h5>
        <ul>
        {% for cooker in dish.cookers.all %}
          <li>{{ cooker.username }}, ({{ cooker.first_name }} {{ cooker.last_name }})</li>
        {% endfor %}
        </ul>
      {% else %}
        <p>There is no cookers</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/restaurant/aperitifs_list.html
{% extends "base.html" %}
{% block content %}
    <h3>Aperitifs recipes: </h3>
  {% if aperitifs_list %}
    <oL>
    {% for aperitifs in aperitifs_list %}
      <li>Aperitifs: <a href="{% url 'catalog:aperitifs-detail' pk=aperitifs.id %}" style="text-decoration: none">{{ aperitifs.name }}</a>, Price: {{ aperitifs.price }} </li>
    {% endfor %}
    </oL>
  {% else %}
  {% endif %}
{% endblock %}

templates/restaurant/cooker_detail.html
{% extends "base.html" %}

{% block content %}
  <h3>Personal info:</h3>
<section class="vh-100 d-flex justify-content-center align-items-start" style="background-color: white;">
  <div class="container py-5">
    <div class="row justify-content-start">
      <div class="col-md-9 col-lg-7 col-xl-5">
        <div class="card-cooker" style="border-radius: 15px; background-color: #fffbf5; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
          <div class="card-body p-4">
            <div class="d-flex text-black">
              <div class="flex-shrink-0">
                <i class="fa-solid fa-user fa-2xl" style="width: 180px; border-radius: 10px;"></i>
              </div>
              <div class="flex-grow-1 ms-3">
                <h5 class="mb-1">{{ cook.username }}</h5>
                <p class="mb-2 pb-1" style="color: #2b2a2a;">{{ cook.first_name}} {{ cook.last_name }}</p>
                <div class="d-flex justify-content-start rounded-3 p-2 mb-2" style="background-color: #efefef;">
                  <div>
                    <p class="small text-muted mb-1">Experience y.o.</p>
                    <p class="mb-0">{{ cook.years_of_experience }}</p>
                  </div>
                  <div class="px-3">
                    <p class="small text-muted mb-1">Dishes</p>
                    <p class="mb-0">{{ cook.dishes.count }}</p>
                  </div>
                </div>
                <div class="d-flex pt-1">
                  <button type="button" class="btn btn-outline-primary me-1 flex-grow-1">Chat</button>
                  <button type="button" class="btn btn-primary flex-grow-1">Follow</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

{% endblock %}

templates/restaurant/desserts_detail.html
{% extends "base.html" %}
{% block content %}
  <h3 style="text-align: center">Detail {{ dish.dish_type.name }} Page</h3>
  <hr>
  <div class="row justify-content-center">
    <div class="detail-page">
      <p><strong>Dessert name:</strong> {{ dish.name }}</p>
      <p><strong>Dessert name:</strong> {{ dish.price }}</p>
      <p><strong>Dessert description: <br> {{ dish.description }}</strong></p>
      {% if dish.cookers%}
        <h5>Cookers:</h5>
        <ul>
        {% for cooker in dish.cookers.all %}
          <li>{{ cooker.username }}, ({{ cooker.first_name }} {{ cooker.last_name }})</li>
        {% endfor %}
        </ul>
      {% else %}
        <p>There is no cookers</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/restaurant/desserts_list.html
{% extends "base.html" %}
{% block content %}
    <h3>Desserts recipes: </h3>
  {% if desserts_list %}
    <oL>
    {% for dessert in desserts_list %}
      <li>Dessert: <a href="{% url 'catalog:desserts-detail' pk=dessert.id %}" style="text-decoration: none">{{ dessert.name }}</a>, Price: {{ dessert.price }} </li>
    {% endfor %}
    </oL>
  {% else %}
  {% endif %}
{% endblock %}

templates/restaurant/food_detail.html
{% extends "base.html" %}
{% block content %}
  <h3 style="text-align: center">Detail {{ dish.dish_type.name }} Page</h3>
  <hr>
  <div class="row justify-content-center">
    <div class="detail-page">
      <p><strong>Pasta name:</strong> {{ dish.name }}</p>
      <p><strong>Pasta name:</strong> {{ dish.price }}</p>
      <p><strong>Pasta description: <br> {{ dish.description }}</strong></p>
      {% if dish.cookers%}
        <h5>Cookers:</h5>
        <ul>
        {% for cooker in dish.cookers.all %}
          <li>{{ cooker.username }}, ({{ cooker.first_name }} {{ cooker.last_name }})</li>
        {% endfor %}
        </ul>
      {% else %}
        <p>There is no cookers</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/restaurant/index.html
{% extends "base.html" %}
{% load static %}
{% block sidebar %}
  {% include "includes/sidebar_main.html" %}
{% endblock %}
{% block content %}
  <section class="jumbotron text-center" style="background-color: white; border-bottom: dashed red;">
    <div class="container black">
      <h1>La Dolce Vita</h1>
      <p class="lead text-muted" style="font-size: 40px"><strong><span style="color: green">Unite Flavors</span>, Share Delights: Add Your Dish to Our Italian
        Culinary Realm!</strong></p>
      <div class="container mt-4">
  <div class="row">
    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><i class="fa-solid fa-list"></i></h5><br>
          <p class="card-text"><strong>Count of dish types: {{ num_dish_types.count }}</strong></p>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><i class="fa-solid fa-pizza-slice"></i></h5><br>
          <p class="card-text"><strong>Count of dishes: {{ num_dishes.count }}+</strong></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><i class="fa-solid fa-fire"></i></h5><br>
          <p class="card-text"><strong>Count of cookers: {{ num_cookers.count }}+</strong></p>
        </div>
      </div>
    </div>
  </div>
</div>

    </div>
  </section>

<div class="container mt-5">
  <div class="row">
    <!-- Category Box 1 -->
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card-categories">
        <div class="card-body">
          <h5 class="card-title"><a href="{% url 'catalog:pasta-list' %}">PASTA</a><i class="fa-solid fa-bowl-food"></i></h5><br>
          <p class="card-text">Embrace the Art of Pasta: Taste Italy's Finest Masterpieces!</p>
        </div>
      </div>
    </div>

    <!-- Category Box 2 -->
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card-categories">
        <div class="card-body">
          <h5 class="card-title"><a href="{% url 'catalog:pizza-list' %}">PIZZA</a><i class="fa-solid fa-pizza-slice"></i></h5><br>
          <p class="card-text">Slice of Italy: Savor the Authenticity of Our Pizzas!</p>
        </div>
      </div>
    </div>

    <!-- Category Box 3 -->
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card-categories">
        <div class="card-body">
          <h5 class="card-title"><a href="{% url 'catalog:aperitifs-list' %}">Aperitifs</a><i class="fa-solid fa-cheese"></i></h5><br>
          <p class="card-text">Indulge in the Italian Prelude: Aperitifs that Stir the Senses!</p>
        </div>
      </div>
    </div>

    <!-- Category Box 4 -->
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card-categories">
        <div class="card-body">
          <h5 class="card-title"><a href="{% url 'catalog:salad-list' %}">Salads</a><i class="fa-solid fa-seedling"></i></h5><br>
          <p class="card-text">Fresh & Flavorful: Taste the Vibrant Essence of Our Italian Salads!</p>
        </div>
      </div>
    </div>

    <!-- Category Box 5 -->
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card-categories">
        <div class="card-body">
          <h5 class="card-title"><a href="{% url 'catalog:main-dishes-list' %}">Main dishes</a><i class="fa-solid fa-plate-wheat"></i></h5><br>
          <p class="card-text">Hearty Italian Delights: Savor the Essence of Our Main Dishes!</p>
        </div>
      </div>
    </div>

    <!-- Category Box 6 -->
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card-categories">
        <div class="card-body">
          <h5 class="card-title"><a href="{% url 'catalog:desserts-list' %}">Desserts</a><i class="fa-solid fa-cake-candles"></i></h5><br>
          <p class="card-text">Sweet Escapes: Dive into the Divine World of Italian Desserts!</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/restaurant/main_dishes_detail.html
{% extends "base.html" %}
{% block content %}
  <h3 style="text-align: center">Detail {{ dish.dish_type.name }} Page</h3>
  <hr>
  <div class="row justify-content-center">
    <div class="detail-page">
      <p><strong>Main Dish name:</strong> {{ dish.name }}</p>
      <p><strong>Main Dish name:</strong> {{ dish.price }}</p>
      <p><strong>Main Dish description: <br> {{ dish.description }}</strong></p>
      {% if dish.cookers%}
        <h5>Cookers:</h5>
        <ul>
        {% for cooker in dish.cookers.all %}
          <li>{{ cooker.username }}, ({{ cooker.first_name }} {{ cooker.last_name }})</li>
        {% endfor %}
        </ul>
      {% else %}
        <p>There is no cookers</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/restaurant/pasta_detail.html
{% extends "base.html" %}
{% block content %}
  <h3 style="text-align: center">Detail {{ dish.dish_type.name }} Page</h3>
  <hr>
  <div class="row justify-content-center">
    <div class="detail-page">
      <p><strong>Pasta name:</strong> {{ dish.name }}</p>
      <p><strong>Pasta name:</strong> {{ dish.price }}</p>
      <p><strong>Pasta description: <br> {{ dish.description }}</strong></p>
      {% if dish.cookers%}
        <h5>Cookers:</h5>
        <ul>
        {% for cooker in dish.cookers.all %}
          <li>{{ cooker.username }}, ({{ cooker.first_name }} {{ cooker.last_name }})</li>
        {% endfor %}
        </ul>
      {% else %}
        <p>There is no cookers</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/restaurant/pasta_list.html
{% extends "base.html" %}
{% block content %}
    <h3>Pasta recipes: </h3>
  {% if pasta_list %}
    <oL>
    {% for pasta in pasta_list %}
      <li>Pasta: <a href="{% url 'catalog:pasta-detail' pk=pasta.id %}" style="text-decoration: none">{{ pasta.name }}</a>, Price: {{ pasta.price }} </li>
    {% endfor %}
    </oL>
  {% else %}
  {% endif %}
{% endblock %}

templates/restaurant/pizza_detail.html
{% extends "base.html" %}
{% block content %}
  <h3 style="text-align: center">Detail {{ dish.dish_type.name }} Page</h3>
  <hr>
  <div class="row justify-content-center">
    <div class="detail-page">
      <p><strong>Pizza name:</strong> {{ dish.name }}</p>
      <p><strong>Pizza name:</strong> {{ dish.price }}</p>
      <p><strong>Pizza description: <br> {{ dish.description }}</strong></p>
      {% if dish.cookers%}
        <h5>Cookers:</h5>
        <ul>
        {% for cooker in dish.cookers.all %}
          <li>{{ cooker.username }}, ({{ cooker.first_name }} {{ cooker.last_name }})</li>
        {% endfor %}
        </ul>
      {% else %}
        <p>There is no cookers</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/restaurant/pizza_list.html
{% extends "base.html" %}
{% block content %}
    <h3>Pizza recipes: </h3>
  {% if pizza_list %}
    <oL>
    {% for pizza in pizza_list %}
      <li>Pizza: <a href="{% url 'catalog:pizza-detail' pk=pizza.id %}" style="text-decoration: none">{{ pizza.name }}</a>, Price: {{ pizza.price }} </li>
    {% endfor %}
    </oL>
  {% else %}
  {% endif %}
{% endblock %}

templates/restaurant/salads_detail.html
{% extends "base.html" %}
{% block content %}
  <h3 style="text-align: center">Detail {{ dish.dish_type.name }} Page</h3>
  <hr>
  <div class="row justify-content-center">
    <div class="detail-page">
      <p><strong>Salad name:</strong> {{ dish.name }}</p>
      <p><strong>Salad name:</strong> {{ dish.price }}</p>
      <p><strong>Salad description: <br> {{ dish.description }}</strong></p>
      {% if dish.cookers%}
        <h5>Cookers:</h5>
        <ul>
        {% for cooker in dish.cookers.all %}
          <li>{{ cooker.username }}, ({{ cooker.first_name }} {{ cooker.last_name }})</li>
        {% endfor %}
        </ul>
      {% else %}
        <p>There is no cookers</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/restaurant/salads_list.html
{% extends "base.html" %}
{% block content %}
    <h3>Salads recipes: </h3>
  {% if salads_list %}
    <oL>
    {% for salad in salads_list %}
      <li>Salad: <a href="{% url 'catalog:salad-detail' pk=salad.id %}" style="text-decoration: none">{{ salad.name }}</a>, Price: {{ salad.price }} </li>
    {% endfor %}
    </oL>
  {% else %}
  {% endif %}
{% endblock %}